# CodeRabbit config
# цель: полностью убрать CodeRabbit из CI/PR checks (не постить commit status)
# и выключить авто-ревью.

language: en-US

enable_free_tier: false

early_access: false

reviews:
  auto_review:
    enabled: false
  auto_incremental_review: false
  commit_status: false
  fail_commit_status: false
  review_status: false
