---

exclude_paths:
  # Tests are intentionally repetitive and should not gate merges on clone detection.
  - "clients/go/**/*_test.go"
  - "clients/rust/**/tests/**"
  - "clients/rust/**/benches/**"
  # Non-executable artifacts (fixtures, matrices, formal Lean pack) are not part of Go/Rust
  # code coverage and must not dilute diff-coverage gates.
  - ".github/**"
  - "conformance/**"
  - "rubin-formal/**"
  - "tools/**"

engines:
  duplication:
    # CLI dispatchers and fixture generators contain inherent structural
    # repetition (dispatch boilerplate, tx-building templates) that cannot be
    # eliminated without sacrificing readability.  Raise the minimum clone
    # threshold so only substantive duplications (>25 lines) are reported.
    exclude_paths:
      - "clients/go/cmd/**"
    config:
      minLines: 25
