# ──────────────────────────────────────────────────────────
# Codacy configuration for Rubin Protocol
# ──────────────────────────────────────────────────────────
# Duplication thresholds:
#   clients/go/   — target < 5% (security-critical, duplication preferred over abstraction)
#   clients/rust/ — target < 5% (same rationale)
#   Cross-client Go↔Rust duplication is architectural (dual-client) and ignored.
#   conformance/, rubin-formal/, tools/, scripts/, analysis/ — excluded entirely.
# ──────────────────────────────────────────────────────────
---

exclude_paths:
  # Tests are intentionally repetitive and should not gate merges on clone detection.
  - "clients/go/**/*_test.go"
  - "clients/rust/**/tests/**"
  - "clients/rust/**/benches/**"
  # Non-executable artifacts (fixtures, matrices, formal Lean pack) are not part of Go/Rust
  # code coverage and must not dilute diff-coverage gates.
  - ".github/**"
  - "conformance/**"
  - "rubin-formal/**"
  - "tools/**"
  # Normative specs (Markdown documents, not code).
  - "spec/**"
  # Shell/JS utility scripts and spec analysis tooling.
  - "scripts/**"
  - "analysis/**"
  # Generated files — deterministic output, not human-authored.
  - "**/*.gen.go"
  - "**/*_generated.rs"
  # Dependency lockfiles.
  - "package-lock.json"

engines:
  duplication:
    # CLI dispatchers and fixture generators contain inherent structural
    # repetition (dispatch boilerplate, tx-building templates) that cannot be
    # eliminated without sacrificing readability.  Raise the minimum clone
    # threshold so only substantive duplications (>25 lines) are reported.
    exclude_paths:
      - "clients/go/cmd/**"
      - "clients/rust/crates/rubin-consensus-cli/**"
    config:
      minLines: 25
