# See .codacy.yml (kept for compatibility with different Codacy setups).
exclude_paths:
  - "conformance/fixtures/**"
  - "conformance/MATRIX.md"
  - "rubin-formal/RubinFormal/Conformance/**"
  - "rubin-formal/RubinFormal/Refinement/GoTraceV1.lean"

exclude_patterns:
  - "conformance/fixtures/**"
  - "conformance/MATRIX.md"
  - "rubin-formal/RubinFormal/Conformance/**"
  - "rubin-formal/RubinFormal/Refinement/GoTraceV1.lean"
