-- AUTOGENERATED: do not edit by hand.
-- Generated from rubin-formal/traces/go_trace_v1.jsonl via tools/formal/gen_lean_refinement_from_traces.py

namespace RubinFormal.Refinement

structure ParseOut where
  id : String
  ok : Bool
  err : String
  consumed : Nat
  txidHex : String
  wtxidHex : String

structure SighashOut where
  id : String
  ok : Bool
  err : String
  digestHex : String

structure PowOut where
  id : String
  op : String
  ok : Bool
  err : String
  targetNewHex : Option String
  blockHashHex : Option String

structure UtxoBasicOut where
  id : String
  ok : Bool
  err : String
  fee : Option Nat
  utxoCount : Option Nat

structure BlockBasicOut where
  id : String
  ok : Bool
  err : String
  blockHashHex : Option String
  sumWeight : Option Nat
  sumDa : Option Nat

structure WeightOut where
  id : String
  ok : Bool
  err : String
  weight : Option Nat
  daBytes : Option Nat
  anchorBytes : Option Nat

structure ValidationOrderOut where
  id : String
  ok : Bool
  err : String
  firstErr : Option String
  evaluated : List String

structure DaIntegrityOut where
  id : String
  ok : Bool
  err : String

structure SimplicityExecOut where
  id : String
  ok : Bool
  err : String
  accepted : Option Bool
  finalCounter : Option Nat

def goTraceFixturesDigestSHA3_256 : String := "4c09ed03829545839e54125e27bdc71eb86d8c61ae44f96bc1cf80c23e94964d"

def parseOuts : List ParseOut := [
  { id := "PARSE-01", ok := true, err := "", consumed := 21, txidHex := "0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", wtxidHex := "0xf760a70e1e838404d8e41679962064dc1bf4fa181699009644a14d0aa389ab4e" },
  { id := "PARSE-16", ok := true, err := "", consumed := 50022, txidHex := "0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", wtxidHex := "0x1f212a9c463bc752002a1e31c7a78a11882780744b5e602157b14d222c403ebe" }
]

def sighashOuts : List SighashOut := [
  { id := "SIGHASH-01", ok := true, err := "", digestHex := "0x2d0c47afbb6533ae5f83a4ca76ee7a2879710b8c5e6492c86a8ea71609a45802" },
  { id := "SIGHASH-02", ok := true, err := "", digestHex := "0xe156ba02d8b1ba785840358da93d3c5b71402bf9853abf9ecbce4cecd139660a" },
  { id := "SIGHASH-03", ok := true, err := "", digestHex := "0xa1a4d8f720145b8a6c2d80f1bd875de24e5c10b700b34fc80b5d469e715196f0" },
  { id := "SIGHASH-04", ok := true, err := "", digestHex := "0xb16e6ccbac98e03ea560452dcfa2f92c29584c9ed787219f25c89f41f43828c0" },
  { id := "SIGHASH-05", ok := true, err := "", digestHex := "0xdaa23cc8b92c706958d428953b0c083017b97ebb53faa0c47c03f4b90a4a6c3f" }
]

def powOuts : List PowOut := [
  { id := "POW-01", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000001234"), blockHashHex := none },
  { id := "POW-02", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000400"), blockHashHex := none },
  { id := "POW-03", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000004000"), blockHashHex := none },
  { id := "POW-03A", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), blockHashHex := none },
  { id := "POW-03C", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000fff"), blockHashHex := none },
  { id := "POW-03D", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000001001"), blockHashHex := none },
  { id := "POW-04", op := "block_hash", ok := true, err := "", targetNewHex := none, blockHashHex := some ("0x6df1cafaee3b81e81e298bc474b514cf8f4ba09e36f527a2d715957dd3360fff") },
  { id := "POW-05", op := "pow_check", ok := true, err := "", targetNewHex := none, blockHashHex := none },
  { id := "POW-08", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000001003"), blockHashHex := none },
  { id := "POW-09", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001"), blockHashHex := none },
  { id := "POW-10", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001"), blockHashHex := none }
]

def utxoBasicOuts : List UtxoBasicOut := [
  { id := "CV-U-06", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-09", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-11", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-13", ok := true, err := "", fee := some 5, utxoCount := some 1 },
  { id := "CV-U-19", ok := true, err := "", fee := some 100, utxoCount := some 0 },
  { id := "CV-U-EXT-01", ok := false, err := "TX_ERR_COVENANT_TYPE_INVALID", fee := none, utxoCount := none },
  { id := "CV-U-EXT-02", ok := false, err := "TX_ERR_COVENANT_TYPE_INVALID", fee := none, utxoCount := none },
  { id := "CV-U-EXT-03", ok := false, err := "TX_ERR_COVENANT_TYPE_INVALID", fee := none, utxoCount := none }
]

def blockBasicOuts : List BlockBasicOut := [
  { id := "CV-B-01", ok := true, err := "", blockHashHex := some ("0x8d79bc005c07a95c60b1ba1539d3bbc112f157c42997413ffe5ffba8c6dc87ee"), sumWeight := some 414, sumDa := some 0 }
]

def weightOuts : List WeightOut := [
  { id := "WEIGHT-01", ok := true, err := "", weight := some 242, daBytes := some 0, anchorBytes := some 0 },
  { id := "WEIGHT-03", ok := true, err := "", weight := some 374, daBytes := some 0, anchorBytes := some 0 },
  { id := "WEIGHT-04", ok := true, err := "", weight := some 1107, daBytes := some 1, anchorBytes := some 32 },
  { id := "WEIGHT-05", ok := true, err := "", weight := some 507, daBytes := some 1, anchorBytes := some 0 }
]

def validationOrderOuts : List ValidationOrderOut := [
  
]

def daIntegrityOuts : List DaIntegrityOut := [
  { id := "CV-DA-01", ok := true, err := "" }
]

def simplicityExecOuts : List SimplicityExecOut := [
  { id := "CV-SE-EXEC-001", ok := true, err := "", accepted := some true, finalCounter := some 400000 },
  { id := "CV-SE-EXEC-002", ok := false, err := "TX_ERR_SIMPLICITY_BUDGET_EXCEEDED", accepted := some true, finalCounter := some 400000 },
  { id := "CV-SE-EXEC-003", ok := false, err := "TX_ERR_SIMPLICITY_REJECTED", accepted := some false, finalCounter := some 3 },
  { id := "CV-SE-MEM-001", ok := true, err := "", accepted := some true, finalCounter := some 1 },
  { id := "CV-SE-MEM-002", ok := false, err := "TX_ERR_SIMPLICITY_BUDGET_EXCEEDED", accepted := some false, finalCounter := some 0 },
  { id := "CV-SE-MEM-003", ok := false, err := "TX_ERR_SIMPLICITY_BUDGET_EXCEEDED", accepted := some false, finalCounter := some 0 },
  { id := "CV-SE-PE-001", ok := true, err := "", accepted := some true, finalCounter := some 1 },
  { id := "CV-SE-PE-002", ok := true, err := "", accepted := some true, finalCounter := some 4 },
  { id := "CV-SE-PE-003", ok := true, err := "", accepted := some true, finalCounter := some 2 },
  { id := "CV-SE-PE-004A", ok := true, err := "", accepted := some true, finalCounter := some 4 },
  { id := "CV-SE-PE-004B", ok := true, err := "", accepted := some true, finalCounter := some 4 },
  { id := "CV-SE-PE-005", ok := true, err := "", accepted := some true, finalCounter := some 64 },
  { id := "CV-SE-PE-006", ok := true, err := "", accepted := some true, finalCounter := some 50000 },
  { id := "CV-SE-PE-007", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-008", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-009", ok := false, err := "TX_ERR_SIMPLICITY_PROGRAM_TOO_LARGE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-010", ok := false, err := "TX_ERR_SIMPLICITY_CMR_MISMATCH", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-011", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-012", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-013", ok := false, err := "TX_ERR_SIMPLICITY_JET_DISALLOWED", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-014", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-015", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-016", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-017", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-PE-018", ok := false, err := "TX_ERR_SIMPLICITY_DECODE", accepted := none, finalCounter := none },
  { id := "CV-SE-REPEAT-001", ok := true, err := "", accepted := some true, finalCounter := some 1 },
  { id := "CV-SE-REPEAT-002", ok := true, err := "", accepted := some true, finalCounter := some 1 }
]

end RubinFormal.Refinement
