-- AUTOGENERATED: do not edit by hand.
-- Generated from rubin-formal/traces/go_trace_v1.jsonl via tools/formal/gen_lean_refinement_from_traces.py

namespace RubinFormal.Refinement

structure ParseOut where
  id : String
  ok : Bool
  err : String
  consumed : Nat
  txidHex : String
  wtxidHex : String

structure SighashOut where
  id : String
  ok : Bool
  err : String
  digestHex : String

structure PowOut where
  id : String
  op : String
  ok : Bool
  err : String
  targetNewHex : Option String
  blockHashHex : Option String

structure UtxoBasicOut where
  id : String
  ok : Bool
  err : String
  fee : Option Nat
  utxoCount : Option Nat

structure BlockBasicOut where
  id : String
  ok : Bool
  err : String
  blockHashHex : Option String
  sumWeight : Option Nat
  sumDa : Option Nat

def goTraceFixturesDigestSHA3_256 : String := "c3263e7db8543e007546701fc11ceb7e9f5e72bf4b1c5f02b7828bce19fd3b83"

def parseOuts : List ParseOut := [
  { id := "PARSE-01", ok := true, err := "", consumed := 21, txidHex := "0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", wtxidHex := "0xf760a70e1e838404d8e41679962064dc1bf4fa181699009644a14d0aa389ab4e" },
  { id := "PARSE-02", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-03", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-04", ok := false, err := "TX_ERR_WITNESS_OVERFLOW", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-05", ok := true, err := "", consumed := 24, txidHex := "0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", wtxidHex := "0xd185596484393174ee58e962e221c00d8a5586ac7c293baa50ac9914022464c1" },
  { id := "PARSE-06", ok := false, err := "TX_ERR_SIG_NONCANONICAL", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-07", ok := false, err := "TX_ERR_WITNESS_OVERFLOW", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-08", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-09", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-10", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-11", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-12", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-13", ok := false, err := "TX_ERR_WITNESS_OVERFLOW", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-14", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-15", ok := false, err := "TX_ERR_PARSE", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" },
  { id := "PARSE-16", ok := false, err := "TX_ERR_WITNESS_OVERFLOW", consumed := 0, txidHex := "0x0000000000000000000000000000000000000000000000000000000000000000", wtxidHex := "0x0000000000000000000000000000000000000000000000000000000000000000" }
]

def sighashOuts : List SighashOut := [
  { id := "SIGHASH-01", ok := true, err := "", digestHex := "0x8d39d12eb7ac2f24532d2d583efbf3feec9449d63e0d66533a3a23522619686d" },
  { id := "SIGHASH-02", ok := true, err := "", digestHex := "0x488afae88a684d1d17435a12f6622e8cec3d452e2307dc09a382a801f3b10601" },
  { id := "SIGHASH-03", ok := true, err := "", digestHex := "0x5df04e7bda6923a0c79260c8aab8b346974d9ba6a48d4f27a8d81eb212e56001" },
  { id := "SIGHASH-04", ok := true, err := "", digestHex := "0xea0c0c75d4ef6393176ec47c75c815321905d52b4856b6432c5d018269446c1b" },
  { id := "SIGHASH-05", ok := true, err := "", digestHex := "0x910b345198d181c730e4f5a955c634fe5a70799b810026c0958f43e333c378a9" }
]

def powOuts : List PowOut := [
  { id := "POW-01", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000001234"), blockHashHex := none },
  { id := "POW-02", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000400"), blockHashHex := none },
  { id := "POW-03", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000004000"), blockHashHex := none },
  { id := "POW-03A", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), blockHashHex := none },
  { id := "POW-03B", op := "retarget_v1", ok := false, err := "TX_ERR_PARSE", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000000"), blockHashHex := none },
  { id := "POW-03C", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000fff"), blockHashHex := none },
  { id := "POW-03D", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000001001"), blockHashHex := none },
  { id := "POW-04", op := "block_hash", ok := true, err := "", targetNewHex := none, blockHashHex := some ("0x6df1cafaee3b81e81e298bc474b514cf8f4ba09e36f527a2d715957dd3360fff") },
  { id := "POW-05", op := "pow_check", ok := true, err := "", targetNewHex := none, blockHashHex := none },
  { id := "POW-06", op := "pow_check", ok := false, err := "BLOCK_ERR_POW_INVALID", targetNewHex := none, blockHashHex := none },
  { id := "POW-07", op := "pow_check", ok := false, err := "BLOCK_ERR_TARGET_INVALID", targetNewHex := none, blockHashHex := none },
  { id := "POW-08", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000001003"), blockHashHex := none },
  { id := "POW-08A", op := "retarget_v1", ok := false, err := "TX_ERR_PARSE", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000000"), blockHashHex := none },
  { id := "POW-09", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001"), blockHashHex := none },
  { id := "POW-10", op := "retarget_v1", ok := true, err := "", targetNewHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001"), blockHashHex := none }
]

def utxoBasicOuts : List UtxoBasicOut := [
  { id := "CV-U-01", ok := false, err := "TX_ERR_MISSING_UTXO", fee := none, utxoCount := none },
  { id := "CV-U-02", ok := false, err := "TX_ERR_MISSING_UTXO", fee := none, utxoCount := none },
  { id := "CV-U-05", ok := false, err := "TX_ERR_VALUE_CONSERVATION", fee := none, utxoCount := none },
  { id := "CV-U-06", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-08", ok := false, err := "TX_ERR_VAULT_OWNER_AUTH_REQUIRED", fee := none, utxoCount := none },
  { id := "CV-U-09", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-10", ok := false, err := "TX_ERR_VALUE_CONSERVATION", fee := none, utxoCount := none },
  { id := "CV-U-11", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-12", ok := false, err := "TX_ERR_VAULT_OUTPUT_NOT_WHITELISTED", fee := none, utxoCount := none },
  { id := "CV-U-13", ok := true, err := "", fee := some 5, utxoCount := some 1 },
  { id := "CV-U-14", ok := false, err := "TX_ERR_TX_NONCE_INVALID", fee := none, utxoCount := none },
  { id := "CV-U-15", ok := false, err := "TX_ERR_SEQUENCE_INVALID", fee := none, utxoCount := none },
  { id := "CV-U-16", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-17", ok := false, err := "TX_ERR_PARSE", fee := none, utxoCount := none },
  { id := "CV-U-18", ok := false, err := "TX_ERR_COVENANT_TYPE_INVALID", fee := none, utxoCount := none },
  { id := "CV-U-EXT-01", ok := true, err := "", fee := some 10, utxoCount := some 1 },
  { id := "CV-U-EXT-02", ok := false, err := "TX_ERR_SIG_NONCANONICAL", fee := none, utxoCount := none },
  { id := "CV-U-EXT-03", ok := false, err := "TX_ERR_COVENANT_TYPE_INVALID", fee := none, utxoCount := none }
]

def blockBasicOuts : List BlockBasicOut := [
  { id := "CV-B-01", ok := true, err := "", blockHashHex := some ("0x8d79bc005c07a95c60b1ba1539d3bbc112f157c42997413ffe5ffba8c6dc87ee"), sumWeight := some 414, sumDa := some 0 },
  { id := "CV-B-02", ok := false, err := "BLOCK_ERR_LINKAGE_INVALID", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-03", ok := false, err := "BLOCK_ERR_MERKLE_INVALID", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-04", ok := false, err := "BLOCK_ERR_TARGET_INVALID", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-05", ok := false, err := "BLOCK_ERR_TARGET_INVALID", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-06", ok := false, err := "BLOCK_ERR_PARSE", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-07", ok := false, err := "BLOCK_ERR_WITNESS_COMMITMENT", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-08", ok := false, err := "BLOCK_ERR_WITNESS_COMMITMENT", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-09", ok := false, err := "TX_ERR_PARSE", blockHashHex := none, sumWeight := none, sumDa := none },
  { id := "CV-B-10", ok := false, err := "TX_ERR_PARSE", blockHashHex := none, sumWeight := none, sumDa := none }
]

end RubinFormal.Refinement
