-- AUTOGENERATED (manual sync): do not edit by hand without updating the source fixture.
-- Source: conformance/fixtures/CV-COMPACT.json

import Std

namespace RubinFormal.Conformance

abbrev Bytes := ByteArray

def bytes (xs : Array UInt8) : Bytes :=
  ⟨xs⟩

inductive CVCompactStateMachineEvent where
  | commit
  | chunk (index : Nat)
  | tick (blocks : Nat)
  | checkblock
deriving DecidableEq

structure CVCompactPhase where
  inIbd : Bool
  warmupDone : Bool
  missRatePct : Nat
  missRateBlocks : Nat

structure CVCompactEvictionEntry where
  daId : String
  fee : Nat
  wireBytes : Nat
  receivedTime : Nat

structure CVCompactCommitEntry where
  daId : String
  peer : String
  fee : Nat

structure CVCompactTelemetry where
  shortidCollisionCount : Option Nat := none
  shortidCollisionBlocks : Option (List String) := none
  shortidCollisionPeers : Option (List String) := none
  daMempoolFillPct : Option Nat := none
  orphanPoolFillPct : Option Nat := none
  missRateBytesL1 : Option Nat := none
  missRateBytesDa : Option Nat := none
  partialSetCount : Option Nat := none
  partialSetAgeP95 : Option Nat := none
  recoverySuccessRatePct : Option Nat := none
  prefetchLatencyMs : Option Nat := none
  peerQualityScore : Option Nat := none

structure CVCompactVector where
  id : String
  op : String
  -- common
  expectOk : Bool
  expectErr : Option String := none

  -- compact_shortid
  wtxid : Option Bytes := none
  nonce1 : Option UInt64 := none
  nonce2 : Option UInt64 := none
  expectShortId : Option Bytes := none

  -- collision fallback
  missingIndices : Option (List Nat) := none
  getblocktxnOk : Option Bool := none
  expectRequestGetblocktxn : Option Bool := none
  expectRequestFullBlock : Option Bool := none
  expectPenalizePeer : Option Bool := none

  -- parse_tx
  tx : Option Bytes := none
  expectTxid : Option Bytes := none
  expectWtxid : Option Bytes := none

  -- witness roundtrip
  suiteId : Option Nat := none
  pubkeyLength : Option Nat := none
  sigLength : Option Nat := none
  expectRoundtripOk : Option Bool := none
  expectWireBytes : Option Nat := none

  -- batch verify
  batchSize : Option Nat := none
  invalidIndices : Option (List Nat) := none
  expectBatchOk : Option Bool := none
  expectFallback : Option Bool := none
  expectInvalidIndices : Option (List Nat) := none

  -- prefill roundtrip
  txCount : Option Nat := none
  prefilledIndices : Option (List Nat) := none
  mempoolIndices : Option (List Nat) := none
  blocktxnIndices : Option (List Nat) := none
  expectMissingIndices : Option (List Nat) := none
  expectReconstructed : Option Bool := none

  -- state machine
  chunkCount : Option Nat := none
  initialChunks : Option (List Nat) := none
  events : Option (List CVCompactStateMachineEvent) := none
  expectFinalState : Option String := none
  expectPinned : Option Bool := none
  expectEvicted : Option Bool := none
  expectTtl : Option Nat := none
  expectTtlResetCount : Option Nat := none
  expectCheckblockResults : Option (List Bool) := none

  -- orphan pool limits
  currentPeerBytes : Option Nat := none
  currentDaIdBytes : Option Nat := none
  currentGlobalBytes : Option Nat := none
  incomingChunkBytes : Option Nat := none
  expectAdmit : Option Bool := none

  -- sendcmpct modes
  phases : Option (List CVCompactPhase) := none
  expectModes : Option (List Nat) := none

  -- peer quality
  startScore : Option Nat := none
  qualityEvents : Option (List String) := none
  expectScore : Option Nat := none
  expectMode : Option Nat := none

  -- prefetch caps
  peerStreamsBps : Option (List Nat) := none
  expectPeerExceeded : Option Bool := none
  expectGlobalExceeded : Option Bool := none
  expectQualityPenalty : Option Bool := none
  expectDisconnect : Option Bool := none

  -- telemetry rate
  completedSets : Option Nat := none
  totalSets : Option Nat := none
  expectRateNumer : Option Nat := none
  expectRateDenom : Option Nat := none

  -- grace period
  gracePeriodBlocks : Option Nat := none
  elapsedBlocks : Option Nat := none
  graceEvents : Option (List String) := none
  expectGraceActive : Option Bool := none

  -- telemetry fields
  telemetry : Option CVCompactTelemetry := none
  expectMissingFields : Option (List String) := none

  -- orphan storm
  globalLimit : Option Nat := none
  incomingHasCommit : Option Bool := none
  recoverySuccessRatePct : Option Nat := none
  observationMinutes : Option Nat := none
  expectStormMode : Option Bool := none
  expectRollback : Option Bool := none

  -- eviction tiebreak
  entries : Option (List CVCompactEvictionEntry) := none
  expectEvictOrder : Option (List String) := none

  -- A->B retention
  commitArrives : Option Bool := none
  expectState : Option String := none
  expectRetainedChunks : Option (List Nat) := none
  expectMissingChunks : Option (List Nat) := none
  expectPrefetchTargets : Option (List Nat) := none
  expectDiscardedChunks : Option (List Nat) := none

  -- duplicate commit
  daId : Option String := none
  commits : Option (List CVCompactCommitEntry) := none
  expectRetainedPeer : Option String := none
  expectDuplicatesDropped : Option Nat := none
  expectPenalizedPeers : Option (List String) := none
  expectReplaced : Option Bool := none

  -- total fee
  commitFee : Option Nat := none
  chunkFees : Option (List Nat) := none
  expectTotalFee : Option Nat := none

  -- pinned accounting
  capBytes : Option Nat := none
  currentPinnedPayloadBytes : Option Nat := none
  incomingPayloadBytes : Option Nat := none
  incomingCommitOverheadBytes : Option Nat := none
  expectCountedBytes : Option Nat := none
  expectIgnoredOverheadBytes : Option Nat := none

  -- storm commit-bearing
  stormTriggerPct : Option Nat := none
  orphanPoolFillPct : Option Nat := none
  containsCommit : Option Bool := none
  containsChunkForKnownCommit : Option Bool := none
  containsBlockWithCommit : Option Bool := none
  expectCommitBearing : Option Bool := none
  expectPrioritize : Option Bool := none
def cvCompactVectors_CV_COMPACT : List CVCompactVector := [
  {
    id := "CV-C-01",
    op := "compact_shortid",
    expectOk := true,
    wtxid := some (bytes #[0x26, 0xce, 0x78, 0xc5, 0x67, 0x1f, 0x12, 0x91, 0x1e, 0x36, 0x10, 0x83, 0x10, 0x95, 0x30, 0x5e, 0xd0, 0x0a, 0x11, 0x2b, 0x9b, 0xa5, 0x9c, 0xdd, 0xb8, 0x7c, 0x69, 0x4b, 0xb8, 0xb4, 0xe6, 0x95]),
    nonce1 := some 506097522914230528,
    nonce2 := some 1084818905618843912,
    expectShortId := some (bytes #[0xb5, 0x0c, 0x6f, 0xb8, 0x6b, 0x2f])
  },
  {
    id := "CV-C-02",
    op := "compact_collision_fallback",
    expectOk := true,
    missingIndices := some [2, 7],
    getblocktxnOk := some false,
    expectRequestGetblocktxn := some true,
    expectRequestFullBlock := some true,
    expectPenalizePeer := some false
  },
  {
    id := "CV-C-03",
    op := "parse_tx",
    expectOk := true,
    tx := some (bytes #[0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]),
    expectTxid := some (bytes #[0x76, 0xf1, 0x3a, 0xd1, 0xaf, 0xe0, 0xe8, 0xef, 0x7c, 0x8b, 0xc2, 0xcc, 0x9c, 0x25, 0x03, 0x7f, 0xfd, 0xfc, 0x44, 0xb1, 0xde, 0xb8, 0xc5, 0x18, 0x12, 0x2f, 0x16, 0xbb, 0xa9, 0xf8, 0x4a, 0x54]),
    expectWtxid := some (bytes #[0x26, 0xce, 0x78, 0xc5, 0x67, 0x1f, 0x12, 0x91, 0x1e, 0x36, 0x10, 0x83, 0x10, 0x95, 0x30, 0x5e, 0xd0, 0x0a, 0x11, 0x2b, 0x9b, 0xa5, 0x9c, 0xdd, 0xb8, 0x7c, 0x69, 0x4b, 0xb8, 0xb4, 0xe6, 0x95])
  },
  {
    id := "CV-C-04",
    op := "parse_tx",
    expectOk := true,
    tx := some (bytes #[0x01, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]),
    expectTxid := some (bytes #[0xab, 0xf5, 0xba, 0x68, 0x5f, 0x88, 0x99, 0x8e, 0xf3, 0x36, 0xe4, 0xba, 0xf0, 0xbd, 0xd9, 0x02, 0xac, 0x4c, 0x9a, 0x5f, 0x30, 0x36, 0x93, 0x3a, 0xd9, 0x1e, 0x67, 0xe2, 0xa1, 0x17, 0x4d, 0x87]),
    expectWtxid := some (bytes #[0x79, 0xb8, 0xa4, 0x99, 0xbc, 0xf2, 0x24, 0x29, 0xf1, 0xde, 0xac, 0x90, 0x38, 0x08, 0x12, 0xd5, 0x6b, 0x2d, 0x81, 0x62, 0x1e, 0x34, 0xc1, 0xd2, 0x00, 0xab, 0xa6, 0x1d, 0x5a, 0x37, 0x5e, 0x80])
  },
  {
    id := "CV-C-05",
    op := "compact_witness_roundtrip",
    expectOk := true,
    suiteId := some 1,
    pubkeyLength := some 2592,
    sigLength := some 4627,
    expectRoundtripOk := some true,
    expectWireBytes := some 7226
  },
  {
    id := "CV-C-06",
    op := "compact_batch_verify",
    expectOk := true,
    batchSize := some 64,
    invalidIndices := some [],
    expectBatchOk := some true,
    expectFallback := some false,
    expectInvalidIndices := some []
  },
  {
    id := "CV-C-07",
    op := "compact_batch_verify",
    expectOk := true,
    batchSize := some 64,
    invalidIndices := some [17],
    expectBatchOk := some false,
    expectFallback := some true,
    expectInvalidIndices := some [17]
  },
  {
    id := "CV-C-08",
    op := "compact_prefill_roundtrip",
    expectOk := true,
    txCount := some 8,
    prefilledIndices := some [0, 3],
    mempoolIndices := some [1, 2, 4, 6, 7],
    blocktxnIndices := some [5],
    expectMissingIndices := some [5],
    expectReconstructed := some true,
    expectRequestFullBlock := some false
  },
  {
    id := "CV-C-09",
    op := "compact_state_machine",
    expectOk := true,
    chunkCount := some 3,
    initialChunks := some [0, 1],
    events := some [.commit, .chunk 2],
    expectFinalState := some "C",
    expectPinned := some true,
    expectEvicted := some false,
    expectTtl := some 3,
    expectTtlResetCount := some 1
  },
  {
    id := "CV-C-10",
    op := "compact_state_machine",
    expectOk := true,
    chunkCount := some 3,
    initialChunks := some [0],
    events := some [.commit, .tick 3],
    expectFinalState := some "EVICTED",
    expectPinned := some false,
    expectEvicted := some true,
    expectTtl := some 0
  },
  {
    id := "CV-C-11",
    op := "compact_state_machine",
    expectOk := true,
    chunkCount := some 2,
    initialChunks := some [],
    events := some [.commit, .checkblock, .chunk 0, .checkblock, .chunk 1, .checkblock],
    expectCheckblockResults := some [false, false, true],
    expectFinalState := some "C",
    expectPinned := some true,
    expectEvicted := some false
  },
  {
    id := "CV-C-12",
    op := "compact_orphan_limits",
    expectOk := true,
    currentPeerBytes := some 4193280,
    currentDaIdBytes := some 0,
    currentGlobalBytes := some 0,
    incomingChunkBytes := some 2048,
    expectAdmit := some false
  },
  {
    id := "CV-C-13",
    op := "compact_orphan_limits",
    expectOk := true,
    currentPeerBytes := some 0,
    currentDaIdBytes := some 8387584,
    currentGlobalBytes := some 0,
    incomingChunkBytes := some 2048,
    expectAdmit := some false
  },
  {
    id := "CV-C-14",
    op := "compact_state_machine",
    expectOk := true,
    chunkCount := some 4,
    initialChunks := some [0],
    events := some [.tick 2, .commit, .tick 2],
    expectFinalState := some "B",
    expectEvicted := some false,
    expectTtlResetCount := some 1,
    expectTtl := some 1
  },
  {
    id := "CV-C-15",
    op := "compact_sendcmpct_modes",
    expectOk := true,
    phases := some [
      { inIbd := true, warmupDone := false, missRatePct := 0, missRateBlocks := 0 },
      { inIbd := false, warmupDone := true, missRatePct := 0, missRateBlocks := 1 },
      { inIbd := false, warmupDone := true, missRatePct := 12, missRateBlocks := 5 }
    ],
    expectModes := some [0, 2, 0]
  },
  {
    id := "CV-C-16",
    op := "compact_peer_quality",
    expectOk := true,
    startScore := some 50,
    qualityEvents := some ["reconstruct_no_getblocktxn", "getblocktxn_required", "full_block_required"],
    expectScore := some 39,
    expectMode := some 0
  },
  {
    id := "CV-C-17",
    op := "compact_prefetch_caps",
    expectOk := true,
    peerStreamsBps := some [4500000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000],
    expectPeerExceeded := some true,
    expectGlobalExceeded := some true,
    expectQualityPenalty := some true,
    expectDisconnect := some false
  },
  {
    id := "CV-C-18",
    op := "compact_telemetry_rate",
    expectOk := true,
    completedSets := some 97,
    totalSets := some 100,
    expectRateNumer := some 97,
    expectRateDenom := some 100
  },
  {
    id := "CV-C-19",
    op := "compact_chunk_count_cap",
    expectOk := false,
    chunkCount := some 62,
    expectErr := some "TX_ERR_PARSE"
  },
  {
    id := "CV-C-20",
    op := "compact_grace_period",
    expectOk := true,
    gracePeriodBlocks := some 1440,
    elapsedBlocks := some 120,
    startScore := some 6,
    graceEvents := some ["full_block_required"],
    expectGraceActive := some true,
    expectScore := some 1,
    expectDisconnect := some false
  },
  {
    id := "CV-C-21",
    op := "compact_grace_period",
    expectOk := true,
    gracePeriodBlocks := some 1440,
    elapsedBlocks := some 1500,
    startScore := some 6,
    graceEvents := some ["full_block_required"],
    expectGraceActive := some false,
    expectScore := some 0,
    expectDisconnect := some true
  },
  {
    id := "CV-C-22",
    op := "compact_telemetry_fields",
    expectOk := true,
    telemetry := some {
      shortidCollisionCount := some 1,
      shortidCollisionBlocks := some ["0000aa"],
      shortidCollisionPeers := some ["peer-1"],
      daMempoolFillPct := some 77,
      orphanPoolFillPct := some 13,
      missRateBytesL1 := some 1,
      missRateBytesDa := some 1,
      partialSetCount := some 2,
      partialSetAgeP95 := some 42,
      recoverySuccessRatePct := some 97,
      prefetchLatencyMs := some 187,
      peerQualityScore := some 61
    }
  },
  {
    id := "CV-C-23",
    op := "compact_telemetry_fields",
    expectOk := false,
    telemetry := some {
      shortidCollisionCount := some 0,
      shortidCollisionBlocks := some [],
      shortidCollisionPeers := some [],
      daMempoolFillPct := some 5,
      orphanPoolFillPct := some 1,
      missRateBytesL1 := some 0,
      missRateBytesDa := some 0,
      partialSetCount := some 0,
      partialSetAgeP95 := some 0,
      prefetchLatencyMs := some 0
    },
    expectMissingFields := some ["peer_quality_score", "recovery_success_rate"]
  },
  {
    id := "CV-C-24",
    op := "compact_orphan_storm",
    expectOk := true,
    globalLimit := some 67108864,
    currentGlobalBytes := some 62914560,
    incomingChunkBytes := some 524288,
    incomingHasCommit := some false,
    recoverySuccessRatePct := some 98,
    observationMinutes := some 5,
    expectStormMode := some true,
    expectAdmit := some false,
    expectRollback := some false
  },
  {
    id := "CV-C-25",
    op := "compact_orphan_storm",
    expectOk := true,
    globalLimit := some 67108864,
    currentGlobalBytes := some 62914560,
    incomingChunkBytes := some 262144,
    incomingHasCommit := some true,
    recoverySuccessRatePct := some 92,
    observationMinutes := some 12,
    expectStormMode := some true,
    expectAdmit := some true,
    expectRollback := some true
  },
  {
    id := "CV-C-26",
    op := "compact_eviction_tiebreak",
    expectOk := true,
    entries := some [
      { daId := "da-02", fee := 1000, wireBytes := 2000, receivedTime := 200 },
      { daId := "da-01", fee := 500, wireBytes := 1000, receivedTime := 100 },
      { daId := "da-03", fee := 500, wireBytes := 1000, receivedTime := 300 }
    ],
    expectEvictOrder := some ["da-01", "da-02", "da-03"]
  },
  {
    id := "CV-C-27",
    op := "compact_a_to_b_retention",
    expectOk := true,
    chunkCount := some 5,
    initialChunks := some [0, 2, 4],
    commitArrives := some true,
    expectState := some "B",
    expectRetainedChunks := some [0, 2, 4],
    expectMissingChunks := some [1, 3],
    expectPrefetchTargets := some [1, 3],
    expectDiscardedChunks := some []
  },
  {
    id := "CV-C-28",
    op := "compact_duplicate_commit",
    expectOk := true,
    daId := some "da-dup",
    commits := some [
      { daId := "da-dup", peer := "peer-a", fee := 5 },
      { daId := "da-dup", peer := "peer-b", fee := 20 },
      { daId := "da-dup", peer := "peer-c", fee := 30 }
    ],
    expectRetainedPeer := some "peer-a",
    expectDuplicatesDropped := some 2,
    expectPenalizedPeers := some ["peer-b", "peer-c"],
    expectReplaced := some false
  },
  {
    id := "CV-C-29",
    op := "compact_total_fee",
    expectOk := true,
    commitFee := some 7,
    chunkFees := some [3, 4, 11],
    expectTotalFee := some 25
  },
  {
    id := "CV-C-30",
    op := "compact_pinned_accounting",
    expectOk := true,
    capBytes := some 96000000,
    currentPinnedPayloadBytes := some 20000000,
    incomingPayloadBytes := some 32000000,
    incomingCommitOverheadBytes := some 1500,
    expectCountedBytes := some 52000000,
    expectIgnoredOverheadBytes := some 1500,
    expectAdmit := some true
  },
  {
    id := "CV-C-31",
    op := "compact_storm_commit_bearing",
    expectOk := true,
    stormTriggerPct := some 90,
    orphanPoolFillPct := some 95,
    containsCommit := some false,
    containsChunkForKnownCommit := some true,
    containsBlockWithCommit := some false,
    expectStormMode := some true,
    expectCommitBearing := some true,
    expectPrioritize := some true,
    expectAdmit := some true
  }
]

end RubinFormal.Conformance
