-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-DA-STRESS.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVDaStressVector where
  id : String
  op : String
  expectOk : Bool
  expectErr : Option String := none
  peerStreamsBps : Option (List Nat) := none
  perPeerBps : Option Nat := none
  globalBps : Option Nat := none
  expectPeerExceeded : Option Bool := none
  expectGlobalExceeded : Option Bool := none
  expectQualityPenalty : Option Bool := none
  expectDisconnect : Option Bool := none
  perPeerLimit : Option Nat := none
  perDaIdLimit : Option Nat := none
  globalLimit : Option Nat := none
  currentPeerBytes : Option Nat := none
  currentDaIdBytes : Option Nat := none
  currentGlobalBytes : Option Nat := none
  incomingChunkBytes : Option Nat := none
  expectAdmit : Option Bool := none
  incomingHasCommit : Option Bool := none
  recoverySuccessRate : Option Nat := none
  observationMinutes : Option Nat := none
  expectFillPct : Option Nat := none
  expectStormMode : Option Bool := none
  expectRollback : Option Bool := none
  capBytes : Option Nat := none
  currentPinnedPayloadBytes : Option Nat := none
  incomingPayloadBytes : Option Nat := none
  incomingCommitOverheadBytes : Option Nat := none
  expectCountedBytes : Option Nat := none
  expectIgnoredOverheadBytes : Option Nat := none
  maxDaChunkCount : Option Nat := none
  chunkCount : Option Nat := none

def cvDaStressVectors : List CVDaStressVector := [
  { id := "CV-DA-STRESS-01", op := "compact_prefetch_caps", expectOk := true, expectErr := none, peerStreamsBps := some [3900000, 3900000, 3900000, 3900000, 3900000, 3900000, 3900000, 3900000], perPeerBps := some 4000000, globalBps := some 32000000, expectPeerExceeded := some false, expectGlobalExceeded := some false, expectQualityPenalty := some false, expectDisconnect := some false, perPeerLimit := none, perDaIdLimit := none, globalLimit := none, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := none, incomingChunkBytes := none, expectAdmit := none, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-02", op := "compact_prefetch_caps", expectOk := true, expectErr := none, peerStreamsBps := some [6100000, 6000000, 6000000, 6000000, 6000000, 6000000, 6000000, 6000000], perPeerBps := some 6000000, globalBps := some 48000000, expectPeerExceeded := some true, expectGlobalExceeded := some true, expectQualityPenalty := some true, expectDisconnect := some false, perPeerLimit := none, perDaIdLimit := none, globalLimit := none, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := none, incomingChunkBytes := none, expectAdmit := none, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-03", op := "compact_orphan_limits", expectOk := true, expectErr := none, peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := some 4194304, perDaIdLimit := some 8388608, globalLimit := some 67108864, currentPeerBytes := some 3145728, currentDaIdBytes := some 7340032, currentGlobalBytes := some 66846720, incomingChunkBytes := some 524288, expectAdmit := some false, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-04", op := "compact_orphan_limits", expectOk := true, expectErr := none, peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := some 6291456, perDaIdLimit := some 12582912, globalLimit := some 100663296, currentPeerBytes := some 5242880, currentDaIdBytes := some 11534336, currentGlobalBytes := some 99614720, incomingChunkBytes := some 524288, expectAdmit := some true, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-05", op := "compact_orphan_storm", expectOk := true, expectErr := none, peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := none, perDaIdLimit := none, globalLimit := some 67108864, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := some 65011712, incomingChunkBytes := some 524288, expectAdmit := some false, incomingHasCommit := some false, recoverySuccessRate := some 98, observationMinutes := some 8, expectFillPct := some 97, expectStormMode := some true, expectRollback := some false, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-06", op := "compact_orphan_storm", expectOk := true, expectErr := none, peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := none, perDaIdLimit := none, globalLimit := some 100663296, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := some 97517568, incomingChunkBytes := some 524288, expectAdmit := some true, incomingHasCommit := some true, recoverySuccessRate := some 93, observationMinutes := some 12, expectFillPct := some 97, expectStormMode := some true, expectRollback := some true, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-07", op := "compact_pinned_accounting", expectOk := true, expectErr := none, peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := none, perDaIdLimit := none, globalLimit := none, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := none, incomingChunkBytes := none, expectAdmit := some true, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := some 96000000, currentPinnedPayloadBytes := some 60000000, incomingPayloadBytes := some 32000000, incomingCommitOverheadBytes := some 2048, expectCountedBytes := some 92000000, expectIgnoredOverheadBytes := some 2048, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-08", op := "compact_pinned_accounting", expectOk := true, expectErr := none, peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := none, perDaIdLimit := none, globalLimit := none, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := none, incomingChunkBytes := none, expectAdmit := some true, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := some 144000000, currentPinnedPayloadBytes := some 90000000, incomingPayloadBytes := some 48000000, incomingCommitOverheadBytes := some 4096, expectCountedBytes := some 138000000, expectIgnoredOverheadBytes := some 4096, maxDaChunkCount := none, chunkCount := none },
  { id := "CV-DA-STRESS-09", op := "compact_chunk_count_cap", expectOk := true, expectErr := none, peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := none, perDaIdLimit := none, globalLimit := none, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := none, incomingChunkBytes := none, expectAdmit := none, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := some 91, chunkCount := some 91 },
  { id := "CV-DA-STRESS-10", op := "compact_chunk_count_cap", expectOk := false, expectErr := some "TX_ERR_PARSE", peerStreamsBps := none, perPeerBps := none, globalBps := none, expectPeerExceeded := none, expectGlobalExceeded := none, expectQualityPenalty := none, expectDisconnect := none, perPeerLimit := none, perDaIdLimit := none, globalLimit := none, currentPeerBytes := none, currentDaIdBytes := none, currentGlobalBytes := none, incomingChunkBytes := none, expectAdmit := none, incomingHasCommit := none, recoverySuccessRate := none, observationMinutes := none, expectFillPct := none, expectStormMode := none, expectRollback := none, capBytes := none, currentPinnedPayloadBytes := none, incomingPayloadBytes := none, incomingCommitOverheadBytes := none, expectCountedBytes := none, expectIgnoredOverheadBytes := none, maxDaChunkCount := some 91, chunkCount := some 92 }
]


end RubinFormal.Conformance
