-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-DEVNET-GENESIS.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVDevnetGenesisUtxo where
  txidHex : String
  vout : Nat
  value : Nat
  covenantType : Nat
  covenantDataHex : String
  creationHeight : Nat
  createdByCoinbase : Bool

inductive CVDevnetGenesisOp where
  | connect_block_basic
  | block_basic_check_with_fees
deriving DecidableEq

structure CVDevnetGenesisVector where
  id : String
  op : CVDevnetGenesisOp
  blockHex : String
  expectedPrevHashHex : Option String
  expectedTargetHex : Option String
  height : Nat
  alreadyGenerated : Nat
  sumFees : Option Nat
  utxos : List CVDevnetGenesisUtxo
  expectOk : Bool
  expectErr : Option String

def cvDevnetGenesisVectors : List CVDevnetGenesisVector := [
  { id := "DEVNET-GENESIS-01", op := .connect_block_basic, blockHex := "0x0100000000000000000000000000000000000000000000000000000000000000000000006f732e615e2f43337a53e9884adba7da32257d5bb5701adc7ed0bd406f2df91340e49e6900000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000101000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff0200407a10f35a0000000021018448b91b88d1a6fbb65e872b72c381b2a9f3ce286a232f56309667f639dd72790000000000000000020020b716a4b7f4c0fab665298ab9b8199b601ab9fa7e0a27f0713383f34cf37071a8000000000000", expectedPrevHashHex := none, expectedTargetHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), height := 0, alreadyGenerated := 0, sumFees := none, utxos := [], expectOk := true, expectErr := none }
]

end RubinFormal.Conformance
