-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-DETERMINISM.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVDeterminismVector where
  id : String
  keys : List String
  expectSortedKeys : List String
  expectOk : Bool

def cvDeterminismVectors : List CVDeterminismVector := [
  { id := "CV-DT-01", keys := ["k3", "k1", "k2"], expectSortedKeys := ["k1", "k2", "k3"], expectOk := true },
  { id := "CV-DT-02", keys := ["0xff", "0x0a", "0x10", "0x01"], expectSortedKeys := ["0x01", "0x0a", "0x10", "0xff"], expectOk := true }
]

end RubinFormal.Conformance
