-- AUTOGENERATED from CV-EXT.json for Q-CONF-CORE-EXT-CV-02.
-- Full Lean replay requires Q-FORMAL-CORE-EXT-01.

namespace RubinFormal.Conformance

structure CVExtVector where
  id : String
  covenantDataHex : String
  expectOk : Bool
  expectErr : Option String

def cvExtVectors : List CVExtVector := [
  { id := "CV-EXT-ENV-01", covenantDataHex := "0x001000", expectOk := true, expectErr := none },
  { id := "CV-EXT-ENV-02", covenantDataHex := "0x01", expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ENV-03", covenantDataHex := "0x001003010203", expectOk := true, expectErr := none },
  { id := "CV-EXT-ENV-04", covenantDataHex := "0x0010050102", expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ACT-01", covenantDataHex := "0x001000", expectOk := true, expectErr := none },
  { id := "CV-EXT-ACT-02", covenantDataHex := "0x00100101", expectOk := true, expectErr := none },
  { id := "CV-EXT-ACT-03", covenantDataHex := "0x002000", expectOk := true, expectErr := none },
  { id := "CV-EXT-PRE-01", covenantDataHex := "0x001000", expectOk := true, expectErr := none },
  { id := "CV-EXT-PRE-02", covenantDataHex := "0x00100101", expectOk := true, expectErr := none },
  { id := "CV-EXT-PRE-03", covenantDataHex := "0x001000", expectOk := true, expectErr := none },
  { id := "CV-EXT-ENF-01", covenantDataHex := "0x00100101", expectOk := true, expectErr := none },
  { id := "CV-EXT-ENF-02", covenantDataHex := "0x00100101", expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" },
  { id := "CV-EXT-ENF-03", covenantDataHex := "0x001000", expectOk := true, expectErr := none },
  { id := "CV-EXT-ENF-04", covenantDataHex := "0x00100101", expectOk := true, expectErr := none },
  { id := "CV-EXT-PAY-01", covenantDataHex := "0x001020000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", expectOk := true, expectErr := none },
  { id := "CV-EXT-PAY-02", covenantDataHex := "0x001000", expectOk := true, expectErr := none },
  { id := "CV-EXT-ERR-01", covenantDataHex := "0x0010050102", expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ERR-02", covenantDataHex := "0xff", expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-ERR-03", covenantDataHex := "0x00100101", expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" },
  { id := "CV-EXT-DUP-01", covenantDataHex := "0x070000", expectOk := false, expectErr := some "TX_ERR_COVENANT_TYPE_INVALID" },
  { id := "CV-EXT-DUP-02", covenantDataHex := "0x070000", expectOk := true, expectErr := none },
  { id := "CV-EXT-GEN-01", covenantDataHex := "0x00100101", expectOk := true, expectErr := none },
  { id := "CV-EXT-GEN-02", covenantDataHex := "0x00100101", expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" },
  { id := "CV-EXT-PAR-01", covenantDataHex := "0x001000", expectOk := true, expectErr := none },
  { id := "CV-EXT-PAR-02", covenantDataHex := "0x00100101", expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID" }
]

end RubinFormal.Conformance
