-- AUTOGENERATED: do not edit by hand.
-- Source: conformance/fixtures/CV-FEATUREBITS.json

namespace RubinFormal.Conformance

structure CVFeaturebitsVector where
  id : String
  name : String
  bit : Nat
  startHeight : Nat
  timeoutHeight : Nat
  height : Nat
  windowSignalCounts : List Nat
  expectOk : Bool
  expectErr : Option String
  expectState : Option String
  expectBoundaryHeight : Option Nat
  expectPrevWindowSignalCount : Option Nat
  expectSignalWindow : Option Nat
  expectSignalThreshold : Option Nat
  expectEstimatedActivationHeight : Option Nat
deriving Repr

def cvFeaturebitsVectors : List CVFeaturebitsVector := [
  { id := "CV-FB-01-defined-before-start"
    name := "X"
    bit := 0
    startHeight := 5000
    timeoutHeight := 100000
    height := 0
    windowSignalCounts := []
    expectOk := true
    expectErr := none
    expectState := some "DEFINED"
    expectBoundaryHeight := some 0
    expectPrevWindowSignalCount := some 0
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := none
  },
  { id := "CV-FB-02-started-at-first-boundary"
    name := "X"
    bit := 0
    startHeight := 1
    timeoutHeight := 100000
    height := 2016
    windowSignalCounts := [1815]
    expectOk := true
    expectErr := none
    expectState := some "STARTED"
    expectBoundaryHeight := some 2016
    expectPrevWindowSignalCount := some 1815
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := none
  },
  { id := "CV-FB-03-single-step-no-double-transition"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    height := 0
    windowSignalCounts := []
    expectOk := true
    expectErr := none
    expectState := some "STARTED"
    expectBoundaryHeight := some 0
    expectPrevWindowSignalCount := some 0
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := none
  },
  { id := "CV-FB-04-lock-in"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    height := 2016
    windowSignalCounts := [1815]
    expectOk := true
    expectErr := none
    expectState := some "LOCKED_IN"
    expectBoundaryHeight := some 2016
    expectPrevWindowSignalCount := some 1815
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := some 4032
  },
  { id := "CV-FB-05-locked-in-to-active"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    height := 4032
    windowSignalCounts := [1815, 0]
    expectOk := true
    expectErr := none
    expectState := some "ACTIVE"
    expectBoundaryHeight := some 4032
    expectPrevWindowSignalCount := some 0
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := none
  },
  { id := "CV-FB-06-timeout-to-failed"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 2016
    height := 2016
    windowSignalCounts := [0]
    expectOk := true
    expectErr := none
    expectState := some "FAILED"
    expectBoundaryHeight := some 2016
    expectPrevWindowSignalCount := some 0
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := none
  },
  { id := "CV-FB-07-lock-in-wins-over-timeout"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 2016
    height := 2016
    windowSignalCounts := [1815]
    expectOk := true
    expectErr := none
    expectState := some "LOCKED_IN"
    expectBoundaryHeight := some 2016
    expectPrevWindowSignalCount := some 1815
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := some 4032
  },
  { id := "CV-FB-08-non-boundary-height-rule"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    height := 2026
    windowSignalCounts := [1815]
    expectOk := true
    expectErr := none
    expectState := some "LOCKED_IN"
    expectBoundaryHeight := some 2016
    expectPrevWindowSignalCount := some 1815
    expectSignalWindow := some 2016
    expectSignalThreshold := some 1815
    expectEstimatedActivationHeight := some 4032
  },
  { id := "CV-FB-09-bit-out-of-range"
    name := "X"
    bit := 32
    startHeight := 0
    timeoutHeight := 1
    height := 0
    windowSignalCounts := []
    expectOk := false
    expectErr := some "featurebits: bit out of range: 32"
    expectState := none
    expectBoundaryHeight := none
    expectPrevWindowSignalCount := none
    expectSignalWindow := none
    expectSignalThreshold := none
    expectEstimatedActivationHeight := none
  }
]

end RubinFormal.Conformance

