-- AUTOGENERATED: do not edit by hand.
-- Source: conformance/fixtures/CV-FLAGDAY.json

namespace RubinFormal.Conformance

structure CVFlagdayVector where
  id : String
  name : String
  bit : Nat
  startHeight : Nat
  timeoutHeight : Nat
  activationHeight : Nat
  height : Nat
  windowSignalCounts : List Nat
  expectOk : Bool
  expectErr : Option String
  expectActivationHeight : Option Nat
  expectConsensusActive : Option Bool
deriving Repr

def cvFlagdayVectors : List CVFlagdayVector := [
  { id := "CV-FD-01-pre-activation"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    activationHeight := 2000
    height := 1999
    windowSignalCounts := []
    expectOk := true
    expectErr := none
    expectActivationHeight := some 2000
    expectConsensusActive := some false
  },
  { id := "CV-FD-02-at-activation"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    activationHeight := 2000
    height := 2000
    windowSignalCounts := []
    expectOk := true
    expectErr := none
    expectActivationHeight := some 2000
    expectConsensusActive := some true
  },
  { id := "CV-FD-03-signaling-ignored-low"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    activationHeight := 2000
    height := 2016
    windowSignalCounts := [0]
    expectOk := true
    expectErr := none
    expectActivationHeight := some 2000
    expectConsensusActive := some true
  },
  { id := "CV-FD-04-signaling-ignored-high"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    activationHeight := 2000
    height := 2016
    windowSignalCounts := [1815]
    expectOk := true
    expectErr := none
    expectActivationHeight := some 2000
    expectConsensusActive := some true
  },
  { id := "CV-FD-05-pre-activation-even-if-locked-in"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    activationHeight := 3000
    height := 2016
    windowSignalCounts := [1815]
    expectOk := true
    expectErr := none
    expectActivationHeight := some 3000
    expectConsensusActive := some false
  },
  { id := "CV-FD-06-consensus-active-even-if-defined"
    name := "X"
    bit := 0
    startHeight := 5000
    timeoutHeight := 100000
    activationHeight := 2000
    height := 2016
    windowSignalCounts := [0]
    expectOk := true
    expectErr := none
    expectActivationHeight := some 2000
    expectConsensusActive := some true
  },
  { id := "CV-FD-07-non-boundary-height-rule"
    name := "X"
    bit := 0
    startHeight := 0
    timeoutHeight := 100000
    activationHeight := 2000
    height := 2026
    windowSignalCounts := [0]
    expectOk := true
    expectErr := none
    expectActivationHeight := some 2000
    expectConsensusActive := some true
  }
]

end RubinFormal.Conformance

