// AUTOGENERATED: do not edit by hand.
// Generated from conformance/fixtures/CV-FORK-CHOICE.json (manual sync until generator supports it).

namespace RubinFormal.Conformance

structure ForkChain where
  id : String
  targets : List String
  tipHash : String
deriving Repr

structure CVForkChoiceVector where
  id : String
  op : String
  target : Option String
  chains : List ForkChain
  expectOk : Bool
  expectWork : Option String
  expectWinner : Option String
deriving Repr

def cvForkChoiceVectors : List CVForkChoiceVector := [
  { id := "CV-FC-01", op := "fork_work", target := some "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", chains := [], expectOk := true, expectWork := some "0x1", expectWinner := none }
  { id := "CV-FC-02", op := "fork_work", target := some "0x8000000000000000000000000000000000000000000000000000000000000000", chains := [], expectOk := true, expectWork := some "0x2", expectWinner := none }
  { id := "CV-FC-03", op := "fork_choice_select", target := none, chains := [
      { id := "A", targets := ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0x8000000000000000000000000000000000000000000000000000000000000000"], tipHash := "0x00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff" }
      { id := "B", targets := ["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff", "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"], tipHash := "0x10112233445566778899aabbccddeeff00112233445566778899aabbccddeeff" }
    ], expectOk := true, expectWork := none, expectWinner := some "A" }
  { id := "CV-FC-04", op := "fork_work", target := some "0x0000000000000000000000000000000000000000000000000000000000000001", chains := [], expectOk := true, expectWork := some "0x10000000000000000000000000000000000000000000000000000000000000000", expectWinner := none }
]

end RubinFormal.Conformance

