// AUTOGENERATED: do not edit by hand.
// Generated from conformance/fixtures/CV-HTLC-ORDERING.json via tools/formal/gen_lean_conformance_vectors.py

namespace RubinFormal.Conformance

structure CVHtlcOrderingVector where
  id : String
  path : String
  structuralOk : Bool
  locktimeOk : Bool
  suiteId : Nat
  blockHeight : Nat
  slhActivationHeight : Nat
  keyBindingOk : Bool
  preimageOk : Bool
  verifyOk : Bool
  expectOk : Bool
  expectErr : Option String
  expectVerifyCalled : Bool
deriving Repr

def cvHtlcOrderingVectors : List CVHtlcOrderingVector := [
  { id := "CV-H-Ordering", path := "claim", structuralOk := true, locktimeOk := true, suiteId := 2, blockHeight := 999999, slhActivationHeight := 1000000, keyBindingOk := true, preimageOk := true, verifyOk := true, expectOk := false, expectErr := some "TX_ERR_SIG_ALG_INVALID", expectVerifyCalled := false }
  { id := "CV-H-Structural-first", path := "claim", structuralOk := false, locktimeOk := true, suiteId := 1, blockHeight := 1000000, slhActivationHeight := 1000000, keyBindingOk := false, preimageOk := false, verifyOk := false, expectOk := false, expectErr := some "TX_ERR_PARSE", expectVerifyCalled := false }
]

end RubinFormal.Conformance
