-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-MERKLE.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVMerkleVector where
  id : String
  txidsHex : List String
  expectOk : Bool
  expectMerkleRootHex : Option String
  expectNotMerkleRootHex : Option String

def cvMerkleVectors : List CVMerkleVector := [
  { id := "MERKLE-01", txidsHex := ["0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0"], expectOk := true, expectMerkleRootHex := some ("0xcc91bf5776e6097dd079c8bc871c8af0b291bb436cb222b4df5b67dca7ebf15e"), expectNotMerkleRootHex := none },
  { id := "MERKLE-02", txidsHex := ["0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", "0xdc17c8ac4e545a2058ba11b4ea304b56db0820a762f4059a496a3ba9b983d5d6"], expectOk := true, expectMerkleRootHex := some ("0x00ba641b6ef898f24ee5740111be08344db28cbd6714ae7dbcdf3d75c648c7bb"), expectNotMerkleRootHex := none },
  { id := "MERKLE-03", txidsHex := ["0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", "0xdc17c8ac4e545a2058ba11b4ea304b56db0820a762f4059a496a3ba9b983d5d6", "0x5f2a5f7a9c5e4bc5c8fe4a41d16ec77cce574f5ec0bd2f7c6f7f2f3f11aa77b1"], expectOk := true, expectMerkleRootHex := some ("0xdf9de20c0dde92db5c88f636299e00c061a63432089a138ae43d368bf54e6730"), expectNotMerkleRootHex := none },
  { id := "MERKLE-04", txidsHex := ["0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", "0xdc17c8ac4e545a2058ba11b4ea304b56db0820a762f4059a496a3ba9b983d5d6", "0x5f2a5f7a9c5e4bc5c8fe4a41d16ec77cce574f5ec0bd2f7c6f7f2f3f11aa77b1", "0x0d69caca2f0f231273962b6adf388b0bdb86f77f731fb5be7c3f9c1b7302de43", "0xf2f4a0f1ef5ff4c8cfb9232d7caea8662f5f31e9f10f8917ac12f90b43f864f8"], expectOk := true, expectMerkleRootHex := some ("0xe60e918a5cc22ee98bf9dbafd96be1a09e08f2c433634a8baacf5366d4c853ba"), expectNotMerkleRootHex := none },
  { id := "CV-MERKLE-ODD-DUP", txidsHex := ["0xd205b2f6296a4cc1e4ec65d1b80309ed98d3a1c03d241c675ff761c6a4502bc0", "0xdc17c8ac4e545a2058ba11b4ea304b56db0820a762f4059a496a3ba9b983d5d6", "0x5f2a5f7a9c5e4bc5c8fe4a41d16ec77cce574f5ec0bd2f7c6f7f2f3f11aa77b1", "0x5f2a5f7a9c5e4bc5c8fe4a41d16ec77cce574f5ec0bd2f7c6f7f2f3f11aa77b1"], expectOk := true, expectMerkleRootHex := some ("0x69c4c7b52eeb183d0a6b64cd7b714953838850115decbbd0ba23b00986b3539f"), expectNotMerkleRootHex := some ("0xdf9de20c0dde92db5c88f636299e00c061a63432089a138ae43d368bf54e6730") }
]


end RubinFormal.Conformance
