-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-MEMPOOL.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVMempoolVector where
  id : String
  txHex : Option String
  expectOk : Bool := true
  expectErr : Option String := none
  fee : Option Nat
  weight : Option Nat
  daBytes : Option Nat
  currentMempoolMinFeeRate : Nat
  minDaFeeRate : Nat
  daSurchargePerByte : Nat
  expectAdmit : Bool
  expectAdmitClass : String
  expectDominantFloor : String
  expectRejectReason : Option String
  expectRelayFeeFloor : Option Nat
  expectDaFeeFloor : Option Nat
  expectDaSurcharge : Option Nat
  expectDaRequiredFee : Option Nat
  expectRequiredFee : Option Nat

def cvMempoolVectors : List CVMempoolVector := [
  { id := "CV-MEMPOOL-01-ROLLING-FLOOR-ACCEPTED", txHex := none, expectOk := true, expectErr := none, fee := some 419, weight := some 418, daBytes := some 0, currentMempoolMinFeeRate := 1, minDaFeeRate := 200, daSurchargePerByte := 200, expectAdmit := true, expectAdmitClass := "accepted", expectDominantFloor := "relay", expectRejectReason := none, expectRelayFeeFloor := some 418, expectDaFeeFloor := some 0, expectDaSurcharge := some 0, expectDaRequiredFee := some 0, expectRequiredFee := some 418 },
  { id := "CV-MEMPOOL-02-ROLLING-FLOOR-UNAVAILABLE", txHex := none, expectOk := true, expectErr := none, fee := some 3383, weight := some 1128, daBytes := some 10, currentMempoolMinFeeRate := 3, minDaFeeRate := 1, daSurchargePerByte := 0, expectAdmit := false, expectAdmitClass := "unavailable", expectDominantFloor := "relay", expectRejectReason := some "MEMPOOL_FEE_BELOW_ROLLING_MINIMUM", expectRelayFeeFloor := some 3384, expectDaFeeFloor := some 10, expectDaSurcharge := some 0, expectDaRequiredFee := some 10, expectRequiredFee := some 3384 },
  { id := "CV-MEMPOOL-03-DA-FLOOR-REJECTED", txHex := none, expectOk := true, expectErr := none, fee := some 1999, weight := some 1128, daBytes := some 10, currentMempoolMinFeeRate := 1, minDaFeeRate := 200, daSurchargePerByte := 0, expectAdmit := false, expectAdmitClass := "rejected", expectDominantFloor := "da", expectRejectReason := some "DA_FEE_BELOW_STAGE_C_FLOOR", expectRelayFeeFloor := some 1128, expectDaFeeFloor := some 2000, expectDaSurcharge := some 0, expectDaRequiredFee := some 2000, expectRequiredFee := some 2000 },
  { id := "CV-MEMPOOL-04-DA-FLOOR-ACCEPTED", txHex := none, expectOk := true, expectErr := none, fee := some 2000, weight := some 1128, daBytes := some 10, currentMempoolMinFeeRate := 1, minDaFeeRate := 200, daSurchargePerByte := 0, expectAdmit := true, expectAdmitClass := "accepted", expectDominantFloor := "da", expectRejectReason := none, expectRelayFeeFloor := some 1128, expectDaFeeFloor := some 2000, expectDaSurcharge := some 0, expectDaRequiredFee := some 2000, expectRequiredFee := some 2000 },
  { id := "CV-MEMPOOL-05-OMITTED-CURRENT-FLOOR-DEFAULT", txHex := none, expectOk := true, expectErr := none, fee := some 1127, weight := some 1128, daBytes := some 10, currentMempoolMinFeeRate := 1, minDaFeeRate := 0, daSurchargePerByte := 0, expectAdmit := false, expectAdmitClass := "unavailable", expectDominantFloor := "relay", expectRejectReason := some "MEMPOOL_FEE_BELOW_ROLLING_MINIMUM", expectRelayFeeFloor := some 1128, expectDaFeeFloor := some 0, expectDaSurcharge := some 0, expectDaRequiredFee := some 0, expectRequiredFee := some 1128 },
  { id := "CV-MEMPOOL-06-MALFORMED-TX-PARSE-FIRST", txHex := some "00", expectOk := false, expectErr := some "TX_ERR_PARSE", fee := none, weight := none, daBytes := none, currentMempoolMinFeeRate := 1, minDaFeeRate := 1, daSurchargePerByte := 1, expectAdmit := false, expectAdmitClass := "", expectDominantFloor := "", expectRejectReason := none, expectRelayFeeFloor := none, expectDaFeeFloor := none, expectDaSurcharge := none, expectDaRequiredFee := none, expectRequiredFee := none }
]


end RubinFormal.Conformance
