-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-NATIVE-ROTATION-DESCRIPTOR.json (manual Lean stub for new gate).

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure RotationDesc where
  name : String
  oldSuiteId : Nat
  newSuiteId : Nat
  createHeight : Nat
  spendHeight : Nat
  sunsetHeight : Nat

structure CVNativeRotationDescriptorVector where
  id : String
  descriptors : List RotationDesc
  expectOk : Bool

def cvNativeRotationDescriptorVectors : List CVNativeRotationDescriptorVector := [
  { id := "NATIVE-ROT-DESC-01", descriptors := [
      { name := "bad-old-eq-new", oldSuiteId := 1, newSuiteId := 1, createHeight := 100, spendHeight := 200, sunsetHeight := 0 }
    ], expectOk := false },
  { id := "NATIVE-ROT-DESC-02", descriptors := [
      { name := "bad-unregistered-old", oldSuiteId := 3, newSuiteId := 2, createHeight := 100, spendHeight := 200, sunsetHeight := 0 }
    ], expectOk := false },
  { id := "NATIVE-ROT-DESC-03", descriptors := [
      { name := "bad-h1-ge-h2", oldSuiteId := 1, newSuiteId := 2, createHeight := 200, spendHeight := 200, sunsetHeight := 0 }
    ], expectOk := false },
  { id := "NATIVE-ROT-DESC-04", descriptors := [
      { name := "bad-h4-le-h2", oldSuiteId := 1, newSuiteId := 2, createHeight := 100, spendHeight := 200, sunsetHeight := 200 }
    ], expectOk := false },
  { id := "NATIVE-ROT-DESC-05", descriptors := [
      { name := "rot-a", oldSuiteId := 1, newSuiteId := 2, createHeight := 100, spendHeight := 200, sunsetHeight := 0 },
      { name := "rot-b", oldSuiteId := 1, newSuiteId := 2, createHeight := 150, spendHeight := 250, sunsetHeight := 0 }
    ], expectOk := false }
]

end RubinFormal.Conformance

