-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-NATIVE-ROTATION-CREATE.json (manual Lean stub for new gate).

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVNativeRotationCreateVector where
  id : String
  height : Nat
  suiteId : Nat
  oldSuiteId : Nat
  newSuiteId : Nat
  createHeight : Nat
  sunsetHeight : Nat
  expectOk : Bool

def cvNativeRotationCreateVectors : List CVNativeRotationCreateVector := [
  { id := "NATIVE-ROT-CREATE-01", height := 199, suiteId := 1, oldSuiteId := 1, newSuiteId := 2, createHeight := 100, sunsetHeight := 0, expectOk := true },
  { id := "NATIVE-ROT-CREATE-02", height := 199, suiteId := 66, oldSuiteId := 1, newSuiteId := 2, createHeight := 100, sunsetHeight := 0, expectOk := false },
  { id := "NATIVE-ROT-CREATE-03", height := 200, suiteId := 2, oldSuiteId := 1, newSuiteId := 2, createHeight := 100, sunsetHeight := 0, expectOk := true },
  { id := "NATIVE-ROT-CREATE-04", height := 200, suiteId := 67, oldSuiteId := 1, newSuiteId := 2, createHeight := 100, sunsetHeight := 0, expectOk := false }
]

end RubinFormal.Conformance

