-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-OUTPUT-DESCRIPTOR.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

inductive ODOp where
  | bytes
  | hash
deriving DecidableEq

structure CVOutputDescriptorVector where
  id : String
  op : ODOp
  covenantType : Nat
  covenantDataHex : String
  expectedHex : String

def cvOutputDescriptorVectors : List CVOutputDescriptorVector := [
  { id := "CV-OD-01", op := .bytes, covenantType := 0, covenantDataHex := "0x01aabbccdd00112233445566778899aabbccddeeff00112233445566778899aabbccddee", expectedHex := "0x00002401aabbccdd00112233445566778899aabbccddeeff00112233445566778899aabbccddee" },
  { id := "CV-OD-02", op := .bytes, covenantType := 257, covenantDataHex := "0x33333333333333333333333333333333333333333333333333333333333333330101111111111111111111111111111111111111111111111111111111111111111101002222222222222222222222222222222222222222222222222222222222222222", expectedHex := "0x01016433333333333333333333333333333333333333333333333333333333333333330101111111111111111111111111111111111111111111111111111111111111111101002222222222222222222222222222222222222222222222222222222222222222" },
  { id := "CV-OD-03", op := .bytes, covenantType := 2, covenantDataHex := "0xdeadbeef", expectedHex := "0x020004deadbeef" },
  { id := "CV-OD-04", op := .hash, covenantType := 0, covenantDataHex := "0x01aabbccdd00112233445566778899aabbccddeeff00112233445566778899aabbccddee", expectedHex := "0xc613ecb3ab48f4f78ee398790f4c40095f699e348b41288a829b9cde419f9beb" }
]

end RubinFormal.Conformance
