-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-POW.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure WindowPattern where
  windowSize : Nat
  start : Nat
  step : Nat
  lastJump : Nat
deriving DecidableEq

inductive CVPowOp where
  | retarget_v1
  | block_hash
  | pow_check
deriving DecidableEq

structure CVPowVector where
  id : String
  op : CVPowOp
  expectOk : Bool
  expectErr : Option String
  targetOldHex : Option String
  timestampFirst : Option Nat
  timestampLast : Option Nat
  windowPattern : Option WindowPattern
  headerHex : Option String
  targetHex : Option String
  expectedBytesHex : Option String

def cvPowVectors : List CVPowVector := [
  { id := "POW-01", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000001234"), timestampFirst := some 100, timestampLast := some 1209700, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000001234") },
  { id := "POW-02", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000001000"), timestampFirst := some 200, timestampLast := some 200, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000000400") },
  { id := "POW-03", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000001000"), timestampFirst := some 0, timestampLast := some 12096000, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000004000") },
  { id := "POW-03A", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), timestampFirst := some 0, timestampLast := some 12096000, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff") },
  { id := "POW-03B", op := .retarget_v1, expectOk := false, expectErr := some "TX_ERR_PARSE", targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000000000"), timestampFirst := some 100, timestampLast := some 200, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := none },
  { id := "POW-03C", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000001000"), timestampFirst := some 0, timestampLast := some 1209599, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000000fff") },
  { id := "POW-03D", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000001000"), timestampFirst := some 0, timestampLast := some 1209900, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000001001") },
  { id := "POW-08", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000001000"), timestampFirst := some 0, timestampLast := some 2209360, windowPattern := some { windowSize := 10080, start := 0, step := 120, lastJump := 1000000 }, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000001003") },
  { id := "POW-08A", op := .retarget_v1, expectOk := false, expectErr := some "TX_ERR_PARSE", targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000001000"), timestampFirst := some 0, timestampLast := some 1209600, windowPattern := some { windowSize := 10080, start := 18446744073709551615, step := 0, lastJump := 0 }, headerHex := none, targetHex := none, expectedBytesHex := none },
  { id := "POW-04", op := .block_hash, expectOk := true, expectErr := none, targetOldHex := none, timestampFirst := none, timestampLast := none, windowPattern := none, headerHex := some ("0x0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), targetHex := none, expectedBytesHex := some ("0x6df1cafaee3b81e81e298bc474b514cf8f4ba09e36f527a2d715957dd3360fff") },
  { id := "POW-05", op := .pow_check, expectOk := true, expectErr := none, targetOldHex := none, timestampFirst := none, timestampLast := none, windowPattern := none, headerHex := some ("0x0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), targetHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), expectedBytesHex := none },
  { id := "POW-06", op := .pow_check, expectOk := false, expectErr := some "BLOCK_ERR_POW_INVALID", targetOldHex := none, timestampFirst := none, timestampLast := none, windowPattern := none, headerHex := some ("0x0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), targetHex := some ("0x6df1cafaee3b81e81e298bc474b514cf8f4ba09e36f527a2d715957dd3360fff"), expectedBytesHex := none },
  { id := "POW-07", op := .pow_check, expectOk := false, expectErr := some "BLOCK_ERR_TARGET_INVALID", targetOldHex := none, timestampFirst := none, timestampLast := none, windowPattern := none, headerHex := some ("0x0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"), targetHex := some ("0x0000000000000000000000000000000000000000000000000000000000000000"), expectedBytesHex := none },
  { id := "POW-09", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001"), timestampFirst := some 0, timestampLast := some 1209000, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001") },
  { id := "POW-10", op := .retarget_v1, expectOk := true, expectErr := none, targetOldHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001"), timestampFirst := some 500000, timestampLast := some 500000, windowPattern := none, headerHex := none, targetHex := none, expectedBytesHex := some ("0x0000000000000000000000000000000000000000000000000000000000000001") }
]

end RubinFormal.Conformance
