-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-REPLAY.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVReplayVector where
  id : String
  op : String
  nonces : List Nat
  expectDuplicates : List Nat
  blockHex : Option String
  expectedPrevHashHex : Option String
  expectedTargetHex : Option String
  prevTimestamps : List Nat
  expectOk : Bool
  expectErr : Option String

def cvReplayVectors : List CVReplayVector := [
  { id := "CV-RP-01", op := "nonce_replay_intrablock", nonces := [1, 2, 3, 4], expectDuplicates := [], blockHex := none, expectedPrevHashHex := none, expectedTargetHex := none, prevTimestamps := [], expectOk := true, expectErr := none },
  { id := "CV-RP-02", op := "nonce_replay_intrablock", nonces := [10, 11, 10, 12], expectDuplicates := [10], blockHex := none, expectedPrevHashHex := none, expectedTargetHex := none, prevTimestamps := [], expectOk := false, expectErr := some "TX_ERR_NONCE_REPLAY" },
  { id := "CV-RP-03", op := "nonce_replay_intrablock", nonces := [21, 21, 22, 23, 22, 24], expectDuplicates := [21, 22], blockHex := none, expectedPrevHashHex := none, expectedTargetHex := none, prevTimestamps := [], expectOk := false, expectErr := some "TX_ERR_NONCE_REPLAY" },
  { id := "CV-RP-04", op := "block_basic_check", nonces := [], expectDuplicates := [], blockHex := some ("0x01000000111111111111111111111111111111111111111111111111111111111111111102380244cc0d5e789d048ecab7c1fd223310d3e372a3921917af67406d4e4e87eb03000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff07000000000000000301000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff01000000000000000002002061a314c23925c3465bd2e979e4961864507bcfa7cd451c8aa84eb4aa9143b1c30500000000000100000000010000000000000001aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0000000000000000000101000000000000000000210100000000000000000000000000000000000000000000000000000000000000000000000000000100000000020000000000000001abababababababababababababababababababababababababababababababab000000000000000000010100000000000000000021010000000000000000000000000000000000000000000000000000000000000000000000000000"), expectedPrevHashHex := some ("0x1111111111111111111111111111111111111111111111111111111111111111"), expectedTargetHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), prevTimestamps := [1000, 1001, 1002, 1003, 1004], expectOk := true, expectErr := none },
  { id := "CV-RP-05", op := "block_basic_check", nonces := [], expectDuplicates := [], blockHex := some ("0x010000001111111111111111111111111111111111111111111111111111111111111111d7070d34ca278b6f8c473ec79b2df4d0f46d9207b0fcbffc9c7ec1cc213d2c02eb03000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff07000000000000000301000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff010000000000000000020020199cf79dcf6d45fef4d90c877931c34354286d6a70aa4893df44f3e957fbbfd30500000000000100000000010000000000000001aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa0000000000000000000101000000000000000000210100000000000000000000000000000000000000000000000000000000000000000000000000000100000000010000000000000001acacacacacacacacacacacacacacacacacacacacacacacacacacacacacacacac000000000000000000010100000000000000000021010000000000000000000000000000000000000000000000000000000000000000000000000000"), expectedPrevHashHex := some ("0x1111111111111111111111111111111111111111111111111111111111111111"), expectedTargetHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), prevTimestamps := [1000, 1001, 1002, 1003, 1004], expectOk := false, expectErr := some "TX_ERR_NONCE_REPLAY" },
  { id := "CV-RP-06", op := "nonce_replay_intrablock", nonces := [100, 101, 102, 103, 100], expectDuplicates := [100], blockHex := none, expectedPrevHashHex := none, expectedTargetHex := none, prevTimestamps := [], expectOk := false, expectErr := some "TX_ERR_NONCE_REPLAY" }
]

end RubinFormal.Conformance
