-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-TIMESTAMP.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVTimestampVector where
  id : String
  op : String
  mtp : Option Nat
  timestamp : Option Nat
  maxFutureDrift : Option Nat
  blockHex : Option String
  expectedPrevHashHex : Option String
  expectedTargetHex : Option String
  prevTimestamps : List Nat
  expectOk : Bool
  expectErr : Option String

def cvTimestampVectors : List CVTimestampVector := [
  { id := "CV-TS-01", op := "timestamp_bounds", mtp := some 1000, timestamp := some 1000, maxFutureDrift := some 7200, blockHex := none, expectedPrevHashHex := none, expectedTargetHex := none, prevTimestamps := [], expectOk := false, expectErr := some "BLOCK_ERR_TIMESTAMP_OLD" },
  { id := "CV-TS-02", op := "timestamp_bounds", mtp := some 1000, timestamp := some 8200, maxFutureDrift := some 7200, blockHex := none, expectedPrevHashHex := none, expectedTargetHex := none, prevTimestamps := [], expectOk := true, expectErr := none },
  { id := "CV-TS-03", op := "timestamp_bounds", mtp := some 1000, timestamp := some 8201, maxFutureDrift := some 7200, blockHex := none, expectedPrevHashHex := none, expectedTargetHex := none, prevTimestamps := [], expectOk := false, expectErr := some "BLOCK_ERR_TIMESTAMP_FUTURE" },
  { id := "CV-TS-05", op := "block_basic_check", mtp := none, timestamp := none, maxFutureDrift := none, blockHex := some ("0x0100000011111111111111111111111111111111111111111111111111111111111111115f62c1d83dfb8efc8be5c8109d541322f26e9b99f1f7ab6bb27deb07924ca804eb03000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff07000000000000000201000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff010000000000000000020020d066e92f294af919b577ea18f3e992551a567c63c377f02ceced1952672f53db0500000000000100000000030000000000000001adadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadad000000000000000000010100000000000000000021010000000000000000000000000000000000000000000000000000000000000000000000000000"), expectedPrevHashHex := some ("0x1111111111111111111111111111111111111111111111111111111111111111"), expectedTargetHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), prevTimestamps := [1000, 1001, 1002, 1003, 1004], expectOk := true, expectErr := none },
  { id := "CV-TS-06", op := "block_basic_check", mtp := none, timestamp := none, maxFutureDrift := none, blockHex := some ("0x0100000011111111111111111111111111111111111111111111111111111111111111115f62c1d83dfb8efc8be5c8109d541322f26e9b99f1f7ab6bb27deb07924ca8040b20000000000000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff07000000000000000201000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000ffffffff00ffffffff010000000000000000020020d066e92f294af919b577ea18f3e992551a567c63c377f02ceced1952672f53db0500000000000100000000030000000000000001adadadadadadadadadadadadadadadadadadadadadadadadadadadadadadadad000000000000000000010100000000000000000021010000000000000000000000000000000000000000000000000000000000000000000000000000"), expectedPrevHashHex := some ("0x1111111111111111111111111111111111111111111111111111111111111111"), expectedTargetHex := some ("0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"), prevTimestamps := [1000, 1001, 1002, 1003, 1004], expectOk := false, expectErr := some "BLOCK_ERR_TIMESTAMP_FUTURE" }
]

end RubinFormal.Conformance
