-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-VAULT-POLICY.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure CVVaultPolicyVector where
  id : String
  vaultInputCount : Nat
  ownerLockId : String
  nonVaultLockIds : List String
  hasOwnerAuth : Bool
  sumInVault : Nat
  sumOut : Nat
  slots : Nat
  keyCount : Nat
  sigThresholdOk : Bool
  sentinelSuiteId : Nat
  sentinelPubkeyLen : Nat
  sentinelSigLen : Nat
  sentinelVerifyCalled : Bool
  whitelist : List String
  validationOrder : Option (List String)
  expectOk : Bool
  expectErr : Option String

def cvVaultPolicyVectors : List CVVaultPolicyVector := [
  { id := "CV-V-01", vaultInputCount := 2, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a"], hasOwnerAuth := true, sumInVault := 100, sumOut := 100, slots := 2, keyCount := 2, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 0, sentinelVerifyCalled := false, whitelist := ["01", "02"], validationOrder := none, expectOk := false, expectErr := some "TX_ERR_VAULT_MULTI_INPUT_FORBIDDEN" },
  { id := "CV-V-02", vaultInputCount := 1, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a", "third-party-b"], hasOwnerAuth := true, sumInVault := 100, sumOut := 100, slots := 1, keyCount := 1, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 0, sentinelVerifyCalled := false, whitelist := ["01", "02"], validationOrder := none, expectOk := false, expectErr := some "TX_ERR_VAULT_FEE_SPONSOR_FORBIDDEN" },
  { id := "CV-V-03", vaultInputCount := 1, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a", "owner-a"], hasOwnerAuth := true, sumInVault := 100, sumOut := 110, slots := 2, keyCount := 2, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 0, sentinelVerifyCalled := false, whitelist := ["01", "02", "03"], validationOrder := none, expectOk := true, expectErr := none },
  { id := "CV-V-04", vaultInputCount := 1, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a"], hasOwnerAuth := true, sumInVault := 100, sumOut := 100, slots := 1, keyCount := 1, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 1, sentinelVerifyCalled := true, whitelist := ["01"], validationOrder := none, expectOk := false, expectErr := some "TX_ERR_PARSE" },
  { id := "CV-V-05", vaultInputCount := 1, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a"], hasOwnerAuth := true, sumInVault := 100, sumOut := 100, slots := 1, keyCount := 1, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 0, sentinelVerifyCalled := false, whitelist := ["02", "01", "02"], validationOrder := none, expectOk := false, expectErr := some "TX_ERR_VAULT_WHITELIST_NOT_CANONICAL" },
  { id := "CV-V-06", vaultInputCount := 2, ownerLockId := "owner-a", nonVaultLockIds := ["third-party-b"], hasOwnerAuth := false, sumInVault := 100, sumOut := 90, slots := 0, keyCount := 2, sigThresholdOk := false, sentinelSuiteId := 1, sentinelPubkeyLen := 32, sentinelSigLen := 20, sentinelVerifyCalled := true, whitelist := ["03", "01", "03"], validationOrder := some ["multi_vault", "owner_auth", "fee_sponsor", "witness_slots", "sentinel", "sig_threshold", "whitelist", "value"], expectOk := false, expectErr := some "TX_ERR_VAULT_MULTI_INPUT_FORBIDDEN" },
  { id := "CV-V-07", vaultInputCount := 1, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a"], hasOwnerAuth := true, sumInVault := 100, sumOut := 100, slots := 1, keyCount := 1, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 0, sentinelVerifyCalled := false, whitelist := ["01", "02"], validationOrder := none, expectOk := true, expectErr := none },
  { id := "CV-V-08", vaultInputCount := 1, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a"], hasOwnerAuth := true, sumInVault := 100, sumOut := 99, slots := 1, keyCount := 1, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 0, sentinelVerifyCalled := false, whitelist := ["01", "02"], validationOrder := none, expectOk := false, expectErr := some "TX_ERR_VALUE_CONSERVATION" },
  { id := "CV-V-09", vaultInputCount := 1, ownerLockId := "owner-a", nonVaultLockIds := ["owner-a"], hasOwnerAuth := true, sumInVault := 100, sumOut := 101, slots := 1, keyCount := 1, sigThresholdOk := true, sentinelSuiteId := 0, sentinelPubkeyLen := 0, sentinelSigLen := 0, sentinelVerifyCalled := false, whitelist := ["01", "02"], validationOrder := none, expectOk := true, expectErr := none }
]

end RubinFormal.Conformance
