-- AUTOGENERATED: do not edit by hand.
-- Generated from conformance/fixtures/CV-VALIDATION-ORDER.json via tools/formal/gen_lean_conformance_vectors.py

set_option maxHeartbeats 10000000
set_option maxRecDepth 50000

namespace RubinFormal.Conformance

structure ValidationCheck where
  name : String
  fails : Bool
  err : String

structure ValidationOrderScenario where
  daSetCount : Nat
  sumDaBytes : Nat
  maxDaBytesPerBlock : Nat
  maxDaBatchesPerBlock : Nat

structure CVValidationOrderVector where
  id : String
  checks : List ValidationCheck
  scenario : Option ValidationOrderScenario
  expectOk : Bool
  expectFirstErr : Option String
  expectEvaluated : List String

def cvValidationOrderVectors : List CVValidationOrderVector := [
  { id := "CV-VO-01", checks := [{ name := "parse", fails := true, err := "BLOCK_ERR_PARSE" }, { name := "target_range", fails := false, err := "BLOCK_ERR_TARGET_INVALID" }, { name := "pow", fails := false, err := "BLOCK_ERR_POW_INVALID" }], scenario := none, expectOk := false, expectFirstErr := some "BLOCK_ERR_PARSE", expectEvaluated := ["parse"] },
  { id := "CV-VO-02", checks := [{ name := "parse", fails := false, err := "BLOCK_ERR_PARSE" }, { name := "target_range", fails := true, err := "BLOCK_ERR_TARGET_INVALID" }, { name := "pow", fails := true, err := "BLOCK_ERR_POW_INVALID" }, { name := "expected_target", fails := true, err := "BLOCK_ERR_TARGET_INVALID" }], scenario := none, expectOk := false, expectFirstErr := some "BLOCK_ERR_TARGET_INVALID", expectEvaluated := ["parse", "target_range"] },
  { id := "CV-VO-03", checks := [{ name := "parse", fails := false, err := "BLOCK_ERR_PARSE" }, { name := "target_range", fails := false, err := "BLOCK_ERR_TARGET_INVALID" }, { name := "pow", fails := false, err := "BLOCK_ERR_POW_INVALID" }, { name := "expected_target", fails := false, err := "BLOCK_ERR_TARGET_INVALID" }, { name := "linkage", fails := false, err := "BLOCK_ERR_LINKAGE_INVALID" }, { name := "merkle", fails := false, err := "BLOCK_ERR_MERKLE_INVALID" }, { name := "witness_commitment", fails := false, err := "BLOCK_ERR_WITNESS_COMMITMENT" }, { name := "timestamp", fails := false, err := "BLOCK_ERR_TIMESTAMP_OLD" }, { name := "weight", fails := true, err := "BLOCK_ERR_WEIGHT_EXCEEDED" }, { name := "anchor_limit", fails := true, err := "BLOCK_ERR_ANCHOR_BYTES_EXCEEDED" }], scenario := none, expectOk := false, expectFirstErr := some "BLOCK_ERR_WEIGHT_EXCEEDED", expectEvaluated := ["parse", "target_range", "pow", "expected_target", "linkage", "merkle", "witness_commitment", "timestamp", "weight"] },
  { id := "CV-VO-04", checks := [{ name := "cursor_p2pk", fails := false, err := "TX_ERR_WITNESS_NONCANONICAL" }, { name := "cursor_htlc", fails := false, err := "TX_ERR_PARSE" }, { name := "cursor_vault", fails := false, err := "TX_ERR_VAULT_MALFORMED" }, { name := "sig_threshold_vault", fails := true, err := "TX_ERR_SIG_INVALID" }, { name := "value_conservation", fails := true, err := "TX_ERR_VALUE_CONSERVATION" }], scenario := none, expectOk := false, expectFirstErr := some "TX_ERR_SIG_INVALID", expectEvaluated := ["cursor_p2pk", "cursor_htlc", "cursor_vault", "sig_threshold_vault"] },
  { id := "CV-VO-05", checks := [{ name := "parse", fails := false, err := "BLOCK_ERR_PARSE" }, { name := "target_range", fails := false, err := "BLOCK_ERR_TARGET_INVALID" }, { name := "pow", fails := false, err := "BLOCK_ERR_POW_INVALID" }, { name := "expected_target", fails := false, err := "BLOCK_ERR_TARGET_INVALID" }, { name := "linkage", fails := false, err := "BLOCK_ERR_LINKAGE_INVALID" }, { name := "merkle", fails := false, err := "BLOCK_ERR_MERKLE_INVALID" }, { name := "witness_commitment", fails := false, err := "BLOCK_ERR_WITNESS_COMMITMENT" }, { name := "timestamp", fails := false, err := "BLOCK_ERR_TIMESTAMP_OLD" }, { name := "weight", fails := true, err := "BLOCK_ERR_WEIGHT_EXCEEDED" }, { name := "da_set_count", fails := false, err := "BLOCK_ERR_DA_BATCH_EXCEEDED" }], scenario := some { daSetCount := 128, sumDaBytes := 32000001, maxDaBytesPerBlock := 32000000, maxDaBatchesPerBlock := 128 }, expectOk := false, expectFirstErr := some "BLOCK_ERR_WEIGHT_EXCEEDED", expectEvaluated := ["parse", "target_range", "pow", "expected_target", "linkage", "merkle", "witness_commitment", "timestamp", "weight"] }
]

end RubinFormal.Conformance
