package consensus

import "fmt"

type ErrorCode string

const (
	TX_ERR_PARSE            ErrorCode = "TX_ERR_PARSE"
	TX_ERR_WITNESS_OVERFLOW ErrorCode = "TX_ERR_WITNESS_OVERFLOW"
	TX_ERR_SIG_NONCANONICAL ErrorCode = "TX_ERR_SIG_NONCANONICAL"
	TX_ERR_SIG_ALG_INVALID  ErrorCode = "TX_ERR_SIG_ALG_INVALID"
	TX_ERR_SIG_INVALID      ErrorCode = "TX_ERR_SIG_INVALID"
	TX_ERR_TIMELOCK_NOT_MET ErrorCode = "TX_ERR_TIMELOCK_NOT_MET"

	TX_ERR_VALUE_CONSERVATION ErrorCode = "TX_ERR_VALUE_CONSERVATION"
	TX_ERR_TX_NONCE_INVALID   ErrorCode = "TX_ERR_TX_NONCE_INVALID"
	TX_ERR_SEQUENCE_INVALID   ErrorCode = "TX_ERR_SEQUENCE_INVALID"
	TX_ERR_NONCE_REPLAY       ErrorCode = "TX_ERR_NONCE_REPLAY"

	TX_ERR_COVENANT_TYPE_INVALID ErrorCode = "TX_ERR_COVENANT_TYPE_INVALID"
	TX_ERR_VAULT_MALFORMED        ErrorCode = "TX_ERR_VAULT_MALFORMED"
	TX_ERR_VAULT_PARAMS_INVALID   ErrorCode = "TX_ERR_VAULT_PARAMS_INVALID"
	TX_ERR_VAULT_KEYS_NOT_CANONICAL ErrorCode = "TX_ERR_VAULT_KEYS_NOT_CANONICAL"
	TX_ERR_VAULT_WHITELIST_NOT_CANONICAL ErrorCode = "TX_ERR_VAULT_WHITELIST_NOT_CANONICAL"
	TX_ERR_VAULT_OWNER_DESTINATION_FORBIDDEN ErrorCode = "TX_ERR_VAULT_OWNER_DESTINATION_FORBIDDEN"
	TX_ERR_VAULT_OWNER_AUTH_REQUIRED ErrorCode = "TX_ERR_VAULT_OWNER_AUTH_REQUIRED"
	TX_ERR_VAULT_FEE_SPONSOR_FORBIDDEN ErrorCode = "TX_ERR_VAULT_FEE_SPONSOR_FORBIDDEN"
	TX_ERR_VAULT_MULTI_INPUT_FORBIDDEN ErrorCode = "TX_ERR_VAULT_MULTI_INPUT_FORBIDDEN"
	TX_ERR_VAULT_OUTPUT_NOT_WHITELISTED ErrorCode = "TX_ERR_VAULT_OUTPUT_NOT_WHITELISTED"
	TX_ERR_MISSING_UTXO          ErrorCode = "TX_ERR_MISSING_UTXO"
	TX_ERR_COINBASE_IMMATURE     ErrorCode = "TX_ERR_COINBASE_IMMATURE"

	BLOCK_ERR_PARSE                     ErrorCode = "BLOCK_ERR_PARSE"
	BLOCK_ERR_WEIGHT_EXCEEDED           ErrorCode = "BLOCK_ERR_WEIGHT_EXCEEDED"
	BLOCK_ERR_ANCHOR_BYTES_EXCEEDED     ErrorCode = "BLOCK_ERR_ANCHOR_BYTES_EXCEEDED"
	BLOCK_ERR_POW_INVALID               ErrorCode = "BLOCK_ERR_POW_INVALID"
	BLOCK_ERR_TARGET_INVALID            ErrorCode = "BLOCK_ERR_TARGET_INVALID"
	BLOCK_ERR_LINKAGE_INVALID           ErrorCode = "BLOCK_ERR_LINKAGE_INVALID"
	BLOCK_ERR_MERKLE_INVALID            ErrorCode = "BLOCK_ERR_MERKLE_INVALID"
	BLOCK_ERR_WITNESS_COMMITMENT        ErrorCode = "BLOCK_ERR_WITNESS_COMMITMENT"
	BLOCK_ERR_COINBASE_INVALID          ErrorCode = "BLOCK_ERR_COINBASE_INVALID"
	BLOCK_ERR_SUBSIDY_EXCEEDED          ErrorCode = "BLOCK_ERR_SUBSIDY_EXCEEDED"
	BLOCK_ERR_TIMESTAMP_OLD             ErrorCode = "BLOCK_ERR_TIMESTAMP_OLD"
	BLOCK_ERR_TIMESTAMP_FUTURE          ErrorCode = "BLOCK_ERR_TIMESTAMP_FUTURE"
	BLOCK_ERR_DA_INCOMPLETE             ErrorCode = "BLOCK_ERR_DA_INCOMPLETE"
	BLOCK_ERR_DA_CHUNK_HASH_INVALID     ErrorCode = "BLOCK_ERR_DA_CHUNK_HASH_INVALID"
	BLOCK_ERR_DA_SET_INVALID            ErrorCode = "BLOCK_ERR_DA_SET_INVALID"
	BLOCK_ERR_DA_PAYLOAD_COMMIT_INVALID ErrorCode = "BLOCK_ERR_DA_PAYLOAD_COMMIT_INVALID"
	BLOCK_ERR_DA_BATCH_EXCEEDED         ErrorCode = "BLOCK_ERR_DA_BATCH_EXCEEDED"
)

type TxError struct {
	Code ErrorCode
	Msg  string
}

func (e *TxError) Error() string {
	if e == nil {
		return "<nil>"
	}
	if e.Msg == "" {
		return string(e.Code)
	}
	return fmt.Sprintf("%s: %s", e.Code, e.Msg)
}

func txerr(code ErrorCode, msg string) error {
	return &TxError{Code: code, Msg: msg}
}
